# Google Playstore Case Study

In this module you’ll be learning data visualisation with the help of a case study. This will enable you to understand how visualisation aids you in solving business problems.

**Problem Statement**

The team at Google Play Store wants to develop a feature that would enable them to boost visibility for the most promising apps. Now, this analysis would require a preliminary understanding of the features that define a well-performing app. You can ask questions like:
- Does a higher size or price necessarily mean that an app would perform better than the other apps?
- Or does a higher number of installs give a clear picture of which app would have a better rating than others?



### Session 1 - Introduction to Data Visualisation

In [ ]:
#import the libraries
import pandas as pd
import numpy as np

In [ ]:
#read the dataset and check the first five rows
df= pd.read_csv('/content/sample_data/hourly_wages_Data_Camp.csv')
print(df.head())

   wage_per_hour  union  education_yrs  experience_yrs  age  female  marr  \
0           5.10      0              8              21   35       1     1
1           4.95      0              9              42   57       1     1
2           6.67      0             12               1   19       0     0
3           4.00      0             12               4   22       0     0
4           7.50      0             12              17   35       0     1

   south  manufacturing  construction
0      0              1             0
1      0              1             0
2      0              1             0
3      0              0             0
4      0              0             0

In [ ]:
#Check the shape of the dataframe
print(df.shape)# it tells the no. of rows and cloumns

(534, 10)

### Data Handling and Cleaning

The first few steps involve making sure that there are no __missing values__ or __incorrect data types__ before we proceed to the analysis stage. These aforementioned problems are handled as follows:

 - For Missing Values: Some common techniques to treat this issue are
    - Dropping the rows containing the missing values
    - Imputing the missing values
    - Keep the missing values if they don't affect the analysis

    
 - Incorrect Data Types:
    - Clean certain values
    - Clean and convert an entire column

In [30]:
#Check the datatypes of all the columns of the dataframe
print(df.dtypes)

wage_per_hour     float64
union               int64
education_yrs       int64
experience_yrs      int64
age                 int64
female              int64
marr                int64
south               int64
manufacturing       int64
construction        int64
dtype: object

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

#### Missing Value Treatment

In [ ]:
#Check the number of null values in the columns
df.isnull().sum()

wage_per_hour     0
union             0
education_yrs     0
experience_yrs    0
age               0
female            0
marr              0
south             0
manufacturing     0
construction      0
dtype: int64

Handling missing values for rating
 - Ratings is the target variable
 - drop the records

In [ ]:
#Drop the rows having null values in the Rating field
# df=df.dropna(subset=['Rating'])
df.columns.tolist()

#Check the shape of the dataframe

['wage_per_hour',
 'union',
 'education_yrs',
 'experience_yrs',
 'age',
 'female',
 'marr',
 'south',
 'manufacturing',
 'construction']

In [ ]:
# Check the number of nulls in the Rating field again to cross-verify

In [ ]:
#Question
#Check the number of nulls in the dataframe again and find the total number of null values

In [ ]:
#Inspect the nulls in the Android Version column

#

In [ ]:
#Drop the row having shifted values

#Check the nulls againin Android version column to cross-verify

Imputing Missing Values

- For numerical variables use mean and median
- For categorical variables use mode

In [ ]:
#Check the most common value in the Android version column

In [ ]:
#Fill up the nulls in the Android Version column with the above value

In [ ]:
#Check the nulls in the Android version column again to cross-verify

In [ ]:
#Check the nulls in the entire dataframe again
df.isnull().sum()

wage_per_hour     0
union             0
education_yrs     0
experience_yrs    0
age               0
female            0
marr              0
south             0
manufacturing     0
construction      0
dtype: int64

In [ ]:
#Check the most common value in the Current version column

In [ ]:
#Replace the nulls in the Current version column with the above value

In [ ]:
# Question : Check the most common value in the Current version column again

#### Handling Incorrect Data Types

In [ ]:
#

In [ ]:
#Question - Try calculating the average price of all apps having the Android version as "4.1 and up"

In [ ]:
#Analyse the Price column to check the issue

In [ ]:
#Write the function to make the changes

In [ ]:
#Verify the dtype of Price once again

In [ ]:
#Analyse the Reviews column

In [ ]:
#Change the dtype of this column


#Check the quantitative spread of this dataframe

In [ ]:
#Analyse the Installs Column

In [ ]:
#Question Clean the Installs Column and find the approximate number of apps at the 50th percentile.

#### Sanity Checks

The data that we have needs to make sense and therefore you can perform certain sanity checks on them to ensure they are factually correct as well. Some sanity checks can be:

- Rating is between 1 and 5 for all the apps.
- Number of Reviews is less than or equal to the number of Installs.
- Free Apps shouldn’t have a price greater than 0.

In [ ]:
#Perform the sanity checks on the Reviews column

In [ ]:
#perform the sanity checks on prices of free apps

#### Outliers Analysis Using Boxplot

Now you need to start identifying and removing extreme values or __outliers__ from our dataset. These values can tilt our analysis and often provide us with a biased perspective of the data available. This is where you’ll start utilising visualisation to achieve your tasks. And the best visualisation to use here would be the box plot. Boxplots are one of the best ways of analysing the spread of a numeric variable


Using a box plot you can identify the outliers as follows:

![BoxPlots to Identify Outliers](images\Boxplot.png)

- Outliers in data can arise due to genuine reasons or because of dubious entries. In the latter case, you should go ahead and remove such entries immediately. Use a boxplot to observe, analyse and remove them.
- In the former case, you should determine whether or not removing them would add value to your analysis procedure.

- You can create a box plot directly from pandas dataframe or the matplotlib way as you learnt in the previous session. Check out their official documentation here:
   - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.boxplot.html
   - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.boxplot.html

In [ ]:
#import the plotting libraries

In [ ]:
#Create a box plot for the price column

In [ ]:
#Check the apps with price more than 200

In [ ]:
#Clean the Price column

In [ ]:
#Create a box plot for paid apps

In [ ]:
#Check the apps with price more than 30

In [ ]:
#Clean the Price column again

### Histograms

Histograms can also be used in conjuction with boxplots for data cleaning and data handling purposes. You can use it to check the spread of a numeric variable. Histograms generally work by bucketing the entire range of values that a particular variable takes to specific __bins__. After that, it uses vertical bars to denote the total number of records in a specific bin, which is also known as its __frequency__.

![Histogram](images\Histogram.png)

You can adjust the number of bins to improve its granularity

![Bins change](images\Granular.png)

You'll be using plt.hist() to plot a histogram. Check out its official documentation:https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html

In [ ]:
#Create a histogram of the Reviews

In [ ]:
#Create a boxplot of the Reviews column

In [ ]:
#Check records with 1 million reviews

In [ ]:
#Drop the above records

In [ ]:
#Question - Create a histogram again and check the peaks

In [ ]:
#Question - Create a box plot for the Installs column and report back the IQR

In [ ]:
#Question - CLean the Installs by removing all the apps having more than or equal to 100 million installs

In [ ]:
#Plot a histogram for Size as well.

In [ ]:
#Question - Create a boxplot for the Size column and report back the median value

### Session 2 - Data Visualisation with Seaborn

Seaborn is Python library to create statistical graphs easily. It is built on top of matplotlib and closely integrated with pandas.

_Functionalities of Seaborn_ :

- Dataset oriented API
- Analysing univariate and bivariate distributions
- Automatic estimation and plotting of  linear regression models
- Convenient views for complex datasets
- Concise control over style
- Colour palettes

In [ ]:
#import the necessary libraries

#### Distribution Plots

A distribution plot is pretty similar to the histogram functionality in matplotlib. Instead of a frequency plot, it plots an approximate probability density for that rating bucket. And the curve (or the __KDE__) that gets drawn over the distribution is the approximate probability density curve.

The following is an example of a distribution plot. Notice that now instead of frequency on the left axis, it has the density for each bin or bucket.

![Distplot](images\Distplot.png)

You'll be using sns.distplot for plotting a distribution plot. Check out its official documentation: https://seaborn.pydata.org/generated/seaborn.distplot.html

In [ ]:
#Create a distribution plot for rating

In [ ]:
#Change the number of bins

In [ ]:
#Change the colour of bins to green

In [ ]:
#Apply matplotlib functionalities

#### Styling Options

One of the biggest advantages of using Seaborn is that you can retain its aesthetic properties and also the Matplotlib functionalities to perform additional customisations. Before we continue with our case study analysis, let’s study some styling options that are available in Seaborn.

-  Check out the official documentation:https://seaborn.pydata.org/generated/seaborn.set_style.html

In [ ]:
#Check all the styling options

In [ ]:
#Change the number of bins to 20

#### Pie-Chart and Bar Chart

For analysing how a numeric variable changes across several categories of a categorical variable you utilise either a pie chart or a box plot

For example, if you want to visualise the responses of a marketing campaign, you can use the following views:

![PieChart](images\pie.png)

![barChart](images\bar.png)

- You'll be using the pandas method of plotting both a pie chart and a bar chart. Check out their official documentations:
   - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.bar.html
   - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.pie.html

In [ ]:
#Analyse the Content Rating column

In [ ]:
#Remove the rows with values which are less represented

In [ ]:
#Reset the index

In [ ]:
#Check the apps belonging to different categories of Content Rating

In [ ]:
#Plot a pie chart

In [ ]:
#Plot a bar chart

In [ ]:
#Question - Plot a bar plot for checking the 4th highest Android version type

#### Scatter Plots

Scatterplots are perhaps one of the most commonly used as well one of the most powerful visualisations you can use in the field of machine learning. They are pretty crucial in revealing relationships between the data points and you can generally deduce some sort of trends in the data with the help of a scatter plot.

![Scatterplot](images\scatter.png)

- They're pretty useful in regression problems to check whether a linear trend exists in the data or not. For example, in the image below, creating a linear model in the first case makes far more sense since a clear straight line trend is visible.

![Scatterplot-Reg](images\regression3.png)

- Also, they help in observing __naturally occuring clusters__. In the following image, the marks of students in Maths and Biology has been plotted.You can clearly group the students to 4 clusters now. Cluster 1 are students who score very well in Biology but very poorly in Maths, Cluster 2 are students who score equally well in both the subjects and so on.

![Scatter-Clusters](images\Clusters.png)

**Note**: You'll be studying about both Regression and Clustering in greater detail in the machine learning modules

You'll be using **sns.jointplot()** for creating a scatter plot. Check out its documentation:
https://seaborn.pydata.org/generated/seaborn.jointplot.html

In [ ]:
###Size vs Rating

##Plot a scatter-plot in the matplotlib way between Size and Rating

In [ ]:
### Plot the same thing now using a jointplot

In [ ]:
## Plot a jointplot for Price and Rating

**Reg Plots**

- These are an extension to the jointplots, where a regression line is added to the view

In [ ]:
##Plot a reg plot for Price and Rating and observe the trend

In [ ]:
## Question - Plot a reg plot for Price and Rating again for only the paid apps.

**Pair Plots**

 - When you have several numeric variables, making multiple scatter plots becomes rather tedious. Therefore, a pair plot visualisation is preferred where all the scatter plots are in a single view in the form of a matrix
 - For the non-diagonal views, it plots a **scatter plot** between 2 numeric variables
 - For the diagonal views, it plots a **histogram**

Pair Plots help in identifying the trends between a target variable and the predictor variables pretty quickly. For example, say you want to predict how your company’s profits are affected by three different factors. In order to choose which you created a pair plot containing profits and the three different factors as the variables. Here are the scatterplots of profits vs the three variables that you obtained from the pair plot.

![Pairplots](images\pairplots2.png)

It is clearly visible that the left-most factor is the most prominently related to the profits, given how linearly scattered the points are and how randomly scattered the rest two factors are.

You'll be using **sns.pairplot()** for this visualisation. Check out its official documentation:https://seaborn.pydata.org/generated/seaborn.pairplot.html

In [ ]:
## Create a pair plot for Reviews, Size, Price and Rating

**Bar Charts Revisited**

- Here, you'll be using bar charts once again, this time using the **sns.barplot()** function. Check out its official documentation:https://seaborn.pydata.org/generated/seaborn.barplot.html
- You can modify the **estimator** parameter to change the aggregation value of your barplot

In [ ]:
##Plot a bar plot of Content Rating vs Average Rating

In [ ]:
##Plot the bar plot again with Median Rating

In [ ]:
##Plot the above bar plot using the estimator parameter

In [ ]:
##Plot the bar plot with only the 5th percentile of Ratings

In [ ]:
##Question - Plot the bar plot with the minimum Rating

__Box Plots Revisited__

- Apart from outlier analysis, box plots are great at comparing the spread and analysing a numerical variable across several categories
- Here you'll be using **sns.boxplot()** function to plot the visualisation. Check out its documentation: https://seaborn.pydata.org/generated/seaborn.boxplot.html

In [ ]:
##Plot a box plot of Rating vs Content Rating

In [ ]:
##Question - Plot a box plot for the Rating column only

In [ ]:
##Question - Plot a box plot of Ratings across the 4 most popular Genres

#### Heat Maps

Heat mapsutilise the concept of using colours and colour intensities to visualise a range of values. You must have seen heat maps in cricket or football broadcasts on television to denote the players’ areas of strength and weakness.

![HeatMap](images\heatmap1.png)

- In python, you can create a heat map whenever you have a rectangular grid or table of numbers analysing any two features

![heatmap2](images\heatmap2.png)

- You'll be using **sns.heatmap()** to plot the visualisation. Checkout its official documentation :https://seaborn.pydata.org/generated/seaborn.heatmap.html

In [ ]:
##Ratings vs Size vs Content Rating

##Prepare buckets for the Size column using pd.qcut

In [ ]:
##Create a pivot table for Size_buckets and Content Rating with values set to Rating

In [ ]:
##Change the aggregation to median

In [ ]:
##Change the aggregation to 20th percentile

In [ ]:
##Store the pivot table in a separate variable

In [ ]:
##Plot a heat map

In [ ]:
##Apply customisations

In [ ]:
##Question - Replace Content Rating with Review_buckets in the above heat map
##Keep the aggregation at minimum value for Rating

### Session 3: Additional Visualisations

#### Line Plots

- A line plot tries to observe trends using time dependent data.
-  For this part, you'll be using **pd.to_datetime()** function. Check out its documentation:https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

In [ ]:
## Extract the month from the Last Updated Date

In [ ]:
## Find the average Rating across all the months

In [ ]:
## Plot a line graph

#### Stacked Bar Charts

- A stacked bar chart breaks down each bar of the bar chart on the basis of a different category
- For example, for the Campaign Response bar chart you saw earlier, the stacked bar chart is also showing the Gender bifurcation as well

![Stacked](images\stacked.png)

In [ ]:
## Create a pivot table for Content Rating and updated Month with the values set to Installs

In [ ]:
##Store the table in a separate variable

In [ ]:
##Plot the stacked bar chart.

In [ ]:
##Plot the stacked bar chart again wrt to the proportions.

#### Plotly

Plotly is a Python library used for creating interactive visual charts. You can take a look at how you can use it to create aesthetic looking plots with a lot of user-friendly functionalities like hover, zoom, etc.

Check out this link for installation and documentation:https://plot.ly/python/getting-started/

In [ ]:
#Install plotly

In [ ]:
#Take the table you want to plot in a separate variable

In [ ]:
#Import the plotly libraries

In [ ]:
#Prepare the plot